export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Locale
export LANG=ko_KR.UTF-8

# Editor
export EDITOR=nvim

# Path
export PATH="$HOME/.local/bin:$PATH"

# Tools
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# Aliases
alias vim=nvim
